trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
  # Build Stage
  - stage: Build
    displayName: 'Build Stage'
    jobs:
      - job: BuildJob
        displayName: 'Build the application'
        steps:
          - bash: echo "Building the application..."
          - bash: java -version
          - bash: node --version
          - bash : echo $(Build.ArtifactStagingDirectory)
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)'
              ArtifactName: 'build'
              publishLocation: 'Container'