trigger:
- main

pool:
  vmImage: ubuntu-latest

jobs:
  # Job 1 depends on job2
  - job: job1
    dependsOn: job2
    steps:
      - script: echo "Hello, world from job1!"
        displayName: 'Run a one-line script in job1'
      
      - script: |
          echo "Adding tasks to build, test, and deploy your project."
          echo "See https://aka.ms/yaml for guidance."
        displayName: 'Run a multi-line script in job1'

  # Job 2 is independent
  - job: job2
    steps:
      - script: echo "Hello, world from job2!"
        displayName: 'Run a one-line script in job2'

  # Job 3 depends on job1
  - job: job3
    dependsOn: job1
    steps:
      - script: echo "Hello, world from job3!"
        displayName: 'Run a one-line script in job3'
