trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
  # Build Stage
  - stage: Build
    displayName: 'Build Stage'
    jobs:
      - job: BuildJob
        displayName: 'Build the application'
        steps:
          - bash: echo "Building the application..."
          - bash: java -version
          - bash: node --version
          - bash: touch helloworld.txt
          - bash: echo "Good Work" > $(Build.ArtifactStagingDirectory)/helloworld.txt
          - bash: cat helloworld.txt
          - bash: ls -lrt
          - bash: pwd
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: '$(Build.SourcesDirectory)'
              ArtifactName: 'build'
              publishLocation: 'Container'
          - task: CopyFiles@2
            inputs:
              SourceFolder: '$(Build.SourcesDirectory)'
              Contents: '**' # Select all files
              TargetFolder: '$(Build.ArtifactStagingDirectory)'
              

  - stage: DEVDeploy
    jobs:
    - deployment: DEVDeployJob
      environment: DEV
      strategy:
       runOnce:
         deploy:
           steps:
             - script: echo "DEV DEPLOY JOB RUNNING"
            

  - stage: QADeploy
    jobs:
    - deployment: QADeployJob
      environment: QA
      strategy:
       runOnce:
         deploy:
           steps:
             - script: echo "QA DEPLOY JOB RUNNING"
      